routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('students', 'App\Http\Controllers\StudentController');
// Route::resource('')

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Task;

class Tag extends Model
{
    use HasFactory;
    protected $fillable =
    [
        'task_id',
        'tag'
    ];

    public function task(){
        return $this->belongsToMany(Task::class);
    }
}

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Task extends Model
{
    use HasFactory;

    protected $fillable = ['tag_id', 'title', 'isCompleted'];

    public function tag(){
        return $this->hasMany(Tag::class,'id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use App\Models\Tag;
use App\Models\Task;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function task(){
        return $this->hasMany(Task::class,'id');
    }

    public function tag(){
        return $this->hasMany(Tag::class,'id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;
use App\Models\Task;
use App\Models\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{
    public function store(Request $request){
        $task = new Task();
        $task->user_id = $request->userId;
        $task->title = $request->title;
        $task->is_completed = $request->is_completed;
        $result = $task->save();

        $task_id = $task->id;

        foreach($request->tags as $tg){
            $tag = new Tag();
            $tag->task_id=$task_id;
            $tag->tag=$tg;
            $tag->save();
        }
        if($result){
            return response()->json(["result"=>"record has been saved ".$task->id]);
        }
        else{
            return response()->json(["result"=>"Operation failed"]);
        }
    }

    public function getAll(Request $request){
        $tasksByUserId = $this->getAllTasksByUserId($request->userId);
        $combinedData = $this->combineAllTagsByTaskId($tasksByUserId);
        return json_encode($combinedData);
    }

    private function getAllTasksByUserId($userId){
        $tasks = Task::where('user_id', $userId)->get();
        return $tasks;
    }

    private function combineAllTagsByTaskId($tasks){
        $taskAndTagsArr = array();
        $tagArr = array();
        foreach($tasks as $task){
            $tagsByTaskId = Tag::where('task_id', $task->id)->get();
            foreach ($tagsByTaskId as $tag) {
                $this->tagArr = array_push(
                    $tagArr,
                    array(
                        'id' => $tag->id,
                        'tag' => $tag->tag
                    )
                );
            }
            $this->taskAndTagsArr = array_push(
                $taskAndTagsArr,
                array(
                    "taskId"=>$task->id,
                    "userId"=>$task->user_id,
                    "title"=>$task->title,
                    "isCompleted"=>$task->is_completed,
                    "tags"=>$tagArr
                )
            );
            $tagArr = array();
        }
        return $taskAndTagsArr;
    }
    
    public function delete($id){
        $tag = Tag::find($id);
        $result = $tag->delete();
        if($result){
            return response()->json(["result"=>"record has been deleted ".$id]);
        }
        else{
            return response()->json(["result"=>"Operation failed"]);
        }
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Task;
use App\Models\Tag;

class TaskController extends Controller
{
    // public function getAll()
    // {
    //     $tasks = Task::all();
    //     return json_encode($tasks);
    // }

    // public function store(Request $request){

    //     $request->validate([
    //         'title' => 'required',
    //         'isCompleted' => 'required'
    //     ]);

    //     try{
    //         Task::create($request->all());
    //         return $this->getAll();
    //     }catch(\Throwable $excep){
    //         return $excep->getMessage();
    //     }
    // }

    public function update(Request $request)
    {
        $task = Task::find($request->id);
        $task->title = $request->newTitle;
        $task->is_completed = $request->is_completed;
        $result = $task->update();
        if($result){
            return response()->json(["result"=>"record has been updated ".$request->id]);
        }
        else{
            return response()->json(["result"=>"Operation failed"]);
        }
    }

    public function delete($id){
        $task = Task::find($id);
        Tag::where('task_id' , '=', $task->id)->delete();

        $result = $task->delete();
        if($result){
            return response()->json(["result"=>"record has been deleted ".$id]);
        }
        else{
            return response()->json(["result"=>"Operation failed"]);
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $user= User::where('email', $request->email)->first();
        if (!$user || !Hash::check($request->password, $user->password)) {
            return response([
                'message' => ['These credentials do not match our records.']
            ], 404);
        }
        $token = $user->createToken('my-app-token')->plainTextToken;
        
        $response = [
            'user' => $user,
            'token' => $token
        ];
        
        return response($response, 201);
    }

    public function register(Request $request){
        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $result = $user->save();

        if($result){
            return response()->json(["result"=>"Register successful"]);
        }
        else{
            return response()->json(["result"=>"Operation failed"]);
        }
    }
}

resources/views/students/create.blade.php
@extends('students.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Student</h2>
        </div>
        <div class="pull-right">
            <a href="{{ route('students.index') }}" class="btn btn-primary"> Back</a>
        </div>
    </div>
</div>

@if($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<form action="{{ route('students.store') }}" method="post">
    @csrf
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Student Name: </strong>
                <input type="text" name="studname" class="form-control">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Course: </strong>
                <input type="text" name="course" class="form-control">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Fee: </strong>
                <input type="text" name="fee" class="form-control">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Country: </strong>
                <input type="text" name="country" class="form-control">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>City: </strong>
                <input type="text" name="city" class="form-control">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/students/edit.blade.php
@extends('students.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Student</h2>
        </div>
        <div class="pull-right">
            <a href="{{ route('students.index') }}" class="btn btn-primary"> Back</a>
        </div>
    </div>
</div>

@if($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<form action="{{ route('students.update', $student->id) }}" method="post">
    @csrf
    @method('PUT')
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Student Name: </strong>
                <input type="text" name="studname" value="{{ $student->studname }}" class="form-control">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Course: </strong>
                <input type="text" name="course" value="{{ $student->course }}" class="form-control">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Fee: </strong>
                <input type="text" name="fee" value="{{ $student->fee }}" class="form-control">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Edit</button>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/students/index.blade.php
@extends('students.layout')

@section('content')
<div class="pull-left">
    <h2>Student CRUD Step by Step</h2>
</div>

<div class="row">
    <div class="col-lg-12 margin-tb padding">
        <div class="pull-right">
            <a href="{{ route('students.create') }}" class="btn btn-success">Create new student</a>
        </div>
    </div>
</div>

@if($message = Session::get('success'))
<div class="alert aler-success">
    <p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Name</th>
        <th>Course</th>
        <th>Fee</th>
        <th>Country</th>
        <th>City</th>
        <th width="280px">Action</th>
    </tr>
    @foreach($students as $student)
    <tr>
        <td>{{ $student->id }}</td>
        <td>{{ $student->studname }}</td>
        <td>{{ $student->course }}</td>
        <td>{{ $student->fee }}</td>
        <td>{{ $student->address->country }}</td>
        <td>{{ $student->address->city }}</td>
        <td>
            <form action="{{ route('students.destroy', $student->id) }}" method="post">
                <a href="{{ route('students.show', $student->id) }}" class="btn btn-info">Show</a>
                <a href="{{ route('students.edit', $student->id) }}" class="btn btn-primary">Edit</a>
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </td>
    </tr>
    @endforeach
</table>

resources/views/students/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Student Management System</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        @yield('content')
    </div>
</body>
</html>

resources/views/students/show.blade.php
@extends('students.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Show Student</h2>
        </div>
        <div class="pull-right">
            <a href="{{ route('students.index') }}" class="btn btn-primary"> Back</a>
        </div>
    </div>
</div>
<form action="{{ route('students.update', $student->id) }}" method="post">
    @csrf
    @method('PUT')
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Student Name: </strong>
                <input type="text" name="studname" value="{{ $student->studname }}" class="form-control">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Course: </strong>
                <input type="text" name="course" value="{{ $student->course }}" class="form-control">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Fee: </strong>
                <input type="text" name="fee" value="{{ $student->fee }}" class="form-control">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Country: </strong>
                <input type="text" name="country" value="{{ $student->address->country }}" class="form-control">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>City: </strong>
                <input type="text" name="city" value="{{ $student->address->city }}" class="form-control">
            </div>
        </div>
    </div>
</form>
@endsection